# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
services:
  - docker
addons:
  apt:
    packages:
    - netcat
os:
  - linux
julia:
  - 1.0
  - nightly
notifications:
  email: false
before_install:
  - docker pull quay.io/dexidp/dex:v2.13.0
  - docker run -d --net=host -v $TRAVIS_BUILD_DIR/test:/dexcfg quay.io/dexidp/dex:v2.13.0 serve /dexcfg/dexconfig.yaml
  - $TRAVIS_BUILD_DIR/test/waitdex.sh
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.clone("https://github.com/tanmaykm/HPack.jl.git"); Pkg.clone("https://github.com/tanmaykm/HTTP2.jl.git"); Pkg.clone("https://github.com/tanmaykm/gRPC.jl.git"); Pkg.clone(pwd()); Pkg.build("DexClient"); Pkg.test("DexClient"; coverage=true)';
